### ISSUE TITLE
Log out icon

### ISSUE THREAD

**Issue by Lazaruz88** [HexaneNetworks/gamepanel-dev#13] opened 2019-01-30 16:38 UTC
**Is your feature request related to a problem? Please describe.**
Log out link can be hard to find

**Describe the solution you'd like**
Move it to the top right corner with a icon

**Describe alternatives you've considered**

**Additional context**
![chrome_2019-01-30_17-36-26](https://user-images.githubusercontent.com/6563500/51996797-c5ef8500-24b5-11e9-8069-0e5e4accbe45.png)

**Comment by stubbo** [comment] 2019-01-30 16:39
dupe of #2

**Closed** 2019-01-30 16:40 UTC
